export const uid='689933391352692897';
export const ld = {
    "casinos": {
        "500casino": {
            "allowWithdraw": true,
            "rate": 0.000600240096038415,
            leaderboard: [
                {
                    rank: 4,
                    "casino_user_id": "surr2",
                    "total_revenue": 79473,
                    "total_wager": 79473,
                    "user_id": "54324321",
                    "casino_id": "500casino",
                    "prev_revenue_checkpoint": null,
                    "curr_revenue_checkpoint": "70000.00",
                    "prev_wager_checkpoint": null,
                    "curr_wager_checkpoint": "70000.00",
                    "total_reward": 947.29,
                    "username": "gaexe_2",
                    "discriminator": "0",
                    "revenue": 35,
                    "wager": 42,
                    "reward": 947.3,
                    "displayAvatarURL": "https://cdn.discordapp.com/embed/avatars/3.png",
                },

                {
                    rank: 3,
                    "casino_user_id": "surr2",
                    "total_revenue": 79473,
                    "total_wager": 79473,
                    "user_id": "689933391352692897",
                    "casino_id": "500casino",
                    "prev_revenue_checkpoint": null,
                    "curr_revenue_checkpoint": "70000.00",
                    "prev_wager_checkpoint": null,
                    "curr_wager_checkpoint": "70000.00",
                    "total_reward": 947.29,
                    "username": "gaexe_2",
                    "discriminator": "0",
                    "revenue": 35,
                    "wager": 42,
                    "reward": 947.3,
                    "displayAvatarURL": "https://cdn.discordapp.com/embed/avatars/3.png",
                },
                {
                    rank: 2,
                    "casino_user_id": "farap34",
                    "total_revenue": 79473,
                    "total_wager": 79473,
                    "user_id": "71352692897",
                    "casino_id": "500casino",
                    "prev_revenue_checkpoint": null,
                    "curr_revenue_checkpoint": "70000.00",
                    "prev_wager_checkpoint": null,
                    "curr_wager_checkpoint": "70000.00",
                    "total_reward": 947.29,
                    "username": "caspt4343e_",
                    "discriminator": "0",
                    "revenue": 500,
                    "wager": 599,
                    "reward": 947.3,
                    "displayAvatarURL": "https://cdn.discordapp.com/embed/avatars/2.png",
                },
            ],
            "balances": [
                {
                    "casino_id": "500casino",
                    "currency_type": "eth",
                    "value": 0.0102040816326531
                },
                {
                    "casino_id": "500casino",
                    "currency_type": "usdt",
                    "value": 1.16626650660264
                }
            ],
            "inverseRate": 1666,
            "referralCode": "REF63435AX7A89OU",
            "referralLink": "https://500.casino/r/REF63435AX7A89OU",

        },
        "razed": {
            "allowWithdraw": true,
            "rate": 1,
            "inverseRate": 1,
            "referralCode": "PasCal",
            "referralLink": "https://www.razed.com/signup/?raf=PasCal",
            "datetime": "10/11/2024, 2:02:01 pm",
            "balances": [
                {
                    "casino_id": "razed",
                    "currency_type": "usd",
                    "value": 0
                }
            ],
            "leaderboard": [
                {
                    "rank": 1,
                    "casino_user_id": "suisui0804",
                    "total_revenue": 79473,
                    "total_wager": 79473,
                    "user_id": "689933391352692897",
                    "casino_id": "razed",
                    "prev_revenue_checkpoint": null,
                    "curr_revenue_checkpoint": "70000.00",
                    "prev_wager_checkpoint": null,
                    "curr_wager_checkpoint": "70000.00",
                    "total_reward": 947.29,
                    "username": "casper.exe_",
                    "discriminator": "0",
                    "displayAvatarURL": "https://cdn.discordapp.com/embed/avatars/5.png",
                    "revenue": 9473,
                    "wager": 9473,
                    "reward": 947.3,
                },
                {
                    rank: 2,
                    "casino_user_id": "suisui0804",
                    "total_revenue": 79473,
                    "total_wager": 79473,
                    "user_id": "43223",
                    "casino_id": "razed",
                    "prev_revenue_checkpoint": null,
                    "curr_revenue_checkpoint": "70000.00",
                    "prev_wager_checkpoint": null,
                    "curr_wager_checkpoint": "70000.00",
                    "total_reward": 947.29,
                    "username": "casper.exe_",
                    "discriminator": "0",
                    "revenue": 3333,
                    "wager": 7337,
                    "reward": 947.3,
                    "displayAvatarURL": "https://cdn.discordapp.com/embed/avatars/1.png",
                },
                {
                    rank: 3,

                    "casino_user_id": "farap34",
                    "total_revenue": 79473,
                    "total_wager": 79473,
                    "user_id": "71352692897",
                    "casino_id": "razed",
                    "prev_revenue_checkpoint": null,
                    "curr_revenue_checkpoint": "70000.00",
                    "prev_wager_checkpoint": null,
                    "curr_wager_checkpoint": "70000.00",
                    "total_reward": 947.29,
                    "username": "caspt4343e_",
                    "discriminator": "0",
                    "revenue": 500,
                    "wager": 599,
                    "reward": 947.3,
                    "displayAvatarURL": "https://cdn.discordapp.com/embed/avatars/2.png",
                },
                {
                    rank: 4,
                    "casino_user_id": "surr2",
                    "total_revenue": 79473,
                    "total_wager": 79473,
                    "user_id": "662662",
                    "casino_id": "razed",
                    "prev_revenue_checkpoint": null,
                    "curr_revenue_checkpoint": "70000.00",
                    "prev_wager_checkpoint": null,
                    "curr_wager_checkpoint": "70000.00",
                    "total_reward": 947.29,
                    "username": "gaexe_2",
                    "discriminator": "0",
                    "revenue": 35,
                    "wager": 42,
                    "reward": 947.3,
                    "displayAvatarURL": "https://cdn.discordapp.com/embed/avatars/3.png",
                },
            ]
        }
    },
    "total": {
        "leaderboard": [
            {
                "revenue": 9473,
                "wager": 9473,
                "reward": 947.3,
                "user_id": "689933391352692897",
                "username": "casper.exe_",
                "discriminator": "0",
                "displayAvatarURL": "https://cdn.discordapp.com/embed/avatars/5.png",
                "rank": 2
            },
            {
                "rank": 5,
                "user_id": "43292897",
                "username": "casper.exe_",
                "discriminator": "0",
                "displayAvatarURL": "https://cdn.discordapp.com/embed/avatars/5.png",
                "revenue": 9473,
                "wager": 9473,
                "reward": 947.3,
            },
            {
                rank: 1,
                "user_id": "43223",
                "casino_id": "razed",
                "username": "casper.exe_",
                "discriminator": "0",
                "revenue": 3333,
                "wager": 7337,
                "reward": 947.3,
                "displayAvatarURL": "https://cdn.discordapp.com/embed/avatars/1.png",
            },
            {
                rank: 3,
                "user_id": "71352692897",
                "username": "caspt4343e_",
                "discriminator": "0",
                "revenue": 500,
                "wager": 599,
                "reward": 947.3,
                "displayAvatarURL": "https://cdn.discordapp.com/embed/avatars/2.png",
            },
            {
                rank: 4,
                "user_id": "6112662",
                "username": "gaexe_2",
                "discriminator": "0",
                "revenue": 35,
                "wager": 42,
                "reward": 947.3,
                "displayAvatarURL": "https://cdn.discordapp.com/embed/avatars/3.png",
            },
        ]
    }
}

export const cuids = {

    "500casino": {
        "user_id": "689933391352692897",
        "casino_id": "500casino",
        "casino_user_id": "63e1c540d827f8499d89cf81",
        "prev_revenue_checkpoint": null,
        "curr_revenue_checkpoint": "4.50",
        "prev_wager_checkpoint": null,
        "curr_wager_checkpoint": "4.00",
        "total_reward": 1
    },
    "razed": {
        "user_id": "689933391352692897",
        "casino_id": "razed",
        "casino_user_id": "suisui0804",
        "prev_revenue_checkpoint": null,
        "curr_revenue_checkpoint": "70000.00",
        "prev_wager_checkpoint": null,
        "curr_wager_checkpoint": "70000.00",
        "total_reward": 947.29
    }

}