export const leaderboard=[
        {
            rank:1,
            "casino_user_id": "suisui0804",
            "total_revenue": 79473,
            "total_wager": 79473,
            "user_id": "43223",
            "casino_id": "razed",
            "prev_revenue_checkpoint": null,
            "curr_revenue_checkpoint": "70000.00",
            "prev_wager_checkpoint": null,
            "curr_wager_checkpoint": "70000.00",
            "total_reward": 947.29,
            "username": "casper.exe_",
            "discriminator": "0",
            "revenue": 3333,
            "wager": 7337,
            "reward": 947.3,
            "displayAvatarURL": "https://cdn.discordapp.com/embed/avatars/1.png",  
        },
        {
            rank:2,

            "casino_user_id": "farap34",
            "total_revenue": 79473,
            "total_wager": 79473,
            "user_id": "71352692897",
            "casino_id": "razed",
            "prev_revenue_checkpoint": null,
            "curr_revenue_checkpoint": "70000.00",
            "prev_wager_checkpoint": null,
            "curr_wager_checkpoint": "70000.00",
            "total_reward": 947.29,
            "username": "caspt4343e_",
            "discriminator": "0",
            "revenue": 500,
            "wager": 599,
            "reward": 947.3,
            "displayAvatarURL": "https://cdn.discordapp.com/embed/avatars/2.png",  
        },
        {
            rank:3,
            "casino_user_id": "surr2",
            "total_revenue": 79473,
            "total_wager": 79473,
            "user_id": "54324321",
            "casino_id": "razed",
            "prev_revenue_checkpoint": null,
            "curr_revenue_checkpoint": "70000.00",
            "prev_wager_checkpoint": null,
            "curr_wager_checkpoint": "70000.00",
            "total_reward": 947.29,
            "username": "gaexe_2",
            "discriminator": "0",
            "revenue": 35,
            "wager": 42,
            "reward": 947.3,
            "displayAvatarURL": "https://cdn.discordapp.com/embed/avatars/3.png",  
        },
        {
            rank:4,
            "casino_user_id": "su84",
            "total_revenue": 79473,
            "total_wager": 79473,
            "user_id": "53241",
            "casino_id": "razed",
            "prev_revenue_checkpoint": null,
            "curr_revenue_checkpoint": "70000.00",
            "prev_wager_checkpoint": null,
            "curr_wager_checkpoint": "70000.00",
            "total_reward": 947.29,
            "username": "raese",
            "discriminator": "0",
            "revenue": 9473,
            "wager": 9473,
            "reward": 947.3,
            "displayAvatarURL": "https://cdn.discordapp.com/embed/avatars/4.png",  
        },
        {
            rank:5,
            "casino_user_id": "suisu04",
            "total_revenue": 79473,
            "total_wager": 79473,
            "user_id": "689933391352692897",
            "casino_id": "razed",
            "prev_revenue_checkpoint": null,
            "curr_revenue_checkpoint": "70000.00",
            "prev_wager_checkpoint": null,
            "curr_wager_checkpoint": "70000.00",
            "total_reward": 947.29,
            "username": "cer.exe_",
            "discriminator": "0",
            "revenue": 573,
            "wager":473,
            "reward": 947.3,
            "displayAvatarURL": "https://cdn.discordapp.com/embed/avatars/5.png",  
        },
    ]
 